### ISSUE TITLE
Undefined symbol when trying to load Cxx

### ISSUE THREAD

**Issue by bad-wolf-jm** [JuliaInterop/Cxx.jl#375] opened 2018-03-15 18:55 UTC
Building the package goes without a hitch, no errors, but typing 'using Cxx' afterward results in:

julia> using Cxx
INFO: Precompiling module Cxx.
ERROR: LoadError: LoadError: could not load library "~/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi"
~/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so: undefined symbol: _ZTVN4llvm2cl3optISsLb0ENS0_6parserISsEEEE

The underlying Julia is 0.6.2

**Comment by VPetukhov** [comment] 2018-04-04 07:59
It's duplicate of https://github.com/Keno/Cxx.jl/issues/373

**Closed** 2019-12-22 18:31 UTC
