### ISSUE TITLE
Precompilation fails on CentOS7

### ISSUE THREAD

**Issue by jmitrevs** [JuliaInterop/Cxx.jl#371] opened 2018-02-09 15:35 UTC
I installed a binary 0.6.2 version of Julia on my desktop, and Pkg.add("Cxx") seemed to proceed fine, but then when I try to use Cxx, I see:
```
julia> using Cxx
INFO: Precompiling module Cxx.
ERROR: LoadError: LoadError: could not load library "/home/jmitrevs/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi"
/home/jmitrevs/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so: undefined symbol: _ZTVN4llvm2cl12basic_parserISsEE
Stacktrace:
 [1] dlopen(::String, ::UInt32) at ./libdl.jl:97
 [2] init_libcxxffi() at /home/jmitrevs/.julia/v0.6/Cxx/src/initialization.jl:20
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/jmitrevs/.julia/v0.6/Cxx/src/initialization.jl, in expression starting on line 22
while loading /home/jmitrevs/.julia/v0.6/Cxx/src/Cxx.jl, in expression starting on line 163
ERROR: Failed to precompile Cxx to /home/jmitrevs/.julia/lib/v0.6/Cxx.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
```
Any ideas what is going on?

**Comment by jingpengw** [comment] 2018-02-23 03:43
I got the same error, this is a duplicate of 
https://github.com/Keno/Cxx.jl/issues/321

**Comment by Element-126** [comment] 2018-05-10 10:56
Same issue here, on latest `master` at the time of writing (`06cfb1fb6698680775e3f91252782ca66ee62c67`).
It happens on a clean install of CentOS 7, with the official Julia 0.6.2 binary. I made sure the cache was cleared before building Cxx.jl.

```julia
julia> using Cxx
INFO: Precompiling module Cxx.
ERROR: LoadError: LoadError: could not load library "/home/user/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi"
/home/user/.julia/v0.6/Cxx/src/../deps/usr/lib/libcxxffi.so: undefined symbol: _ZTVN4llvm2cl12basic_parserISsEE
Stacktrace:
 [1] dlopen(::String, ::UInt32) at ./libdl.jl:97
 [2] init_libcxxffi() at /home/user/.julia/v0.6/Cxx/src/initialization.jl:20
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/user/.julia/v0.6/Cxx/src/initialization.jl, in expression starting on line 22
while loading /home/user/.julia/v0.6/Cxx/src/Cxx.jl, in expression starting on line 164
ERROR: Failed to precompile Cxx to /home/user/.julia/lib/v0.6/Cxx.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
```
Has anyone found a workaround for this issue ?

**Comment by Gnimuc** [comment] 2019-04-23 14:19
dup and obsoleted, so closed.

**Closed by Gnimuc** 2019-04-23 14:19 UTC
