### ISSUE TITLE
Precompile error: "undefined symbol: jl_LLVMContext"

### ISSUE THREAD

**Issue by originalsouth** [JuliaInterop/Cxx.jl#500] opened 2023-05-17 09:41 UTC
After adding and building the package the package crashes upon loading in the precompilation step with the following error:
```
[ Info: Precompiling Cxx [a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2]
ERROR: LoadError: could not load library "/home/user/.julia/packages/Cxx/1RaOv/src/../deps/usr/lib/libcxxffi"
/home/user/.julia/packages/Cxx/1RaOv/src/../deps/usr/lib/libcxxffi.so: undefined symbol: jl_LLVMContext
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen
    @ ./libdl.jl:116 [inlined]
  [3] init_libcxxffi()
    @ Cxx.CxxCore ~/.julia/packages/Cxx/1RaOv/src/initialization.jl:23
  [4] top-level scope
    @ ~/.julia/packages/Cxx/1RaOv/src/initialization.jl:25
  [5] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
  [6] include(x::String)
    @ Cxx.CxxCore ~/.julia/packages/Cxx/1RaOv/src/Cxx.jl:144
  [7] top-level scope
    @ ~/.julia/packages/Cxx/1RaOv/src/Cxx.jl:170
  [8] include
    @ ./Base.jl:457 [inlined]
  [9] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2010
 [10] top-level scope
    @ stdin:2
in expression starting at /home/user/.julia/packages/Cxx/1RaOv/src/initialization.jl:25
in expression starting at /home/user/.julia/packages/Cxx/1RaOv/src/Cxx.jl:142
in expression starting at stdin:2
ERROR: Failed to precompile Cxx [a0b5b9ef-44b7-5148-a2d1-f6db19f3c3d2] to "/home/user/.julia/compiled/v1.9/Cxx/jl_1dUmit".
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2260
 [3] compilecache
   @ ./loading.jl:2127 [inlined]
 [4] _require(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:1770
 [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:1625
 [6] macro expansion
   @ ./loading.jl:1613 [inlined]
 [7] macro expansion
   @ ./lock.jl:267 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1576
```
Version info:
```
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 5800U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 1 on 16 virtual cores
```

**Comment by stevengj** [comment] 2023-08-14 17:15
This package doesn't support recent Julia versions, unfortunately.  Duplicate of #487

**Closed by stevengj** 2023-08-14 17:15 UTC
