### ISSUE TITLE
still the pakage cannot compile in Julia 0.7-DEV

### ISSUE THREAD

**Issue by DrKrar** [JuliaInterop/Cxx.jl#358] opened 2017-09-28 22:12 UTC
using Cxx 
did not scuceeded with the Error:

ERROR: LoadError: LoadError: could not open file E:\Users\DrKra\.julia\v0.7\Cxx\src\../deps/build/clang_constants.jl
Stacktrace:
 [1] include_relative(::Module, ::String) at .\loading.jl:464
 [2] include at .\sysimg.jl:14 [inlined]
 [3] include(::String) at E:\Users\DrKra\.julia\v0.7\Cxx\src\Cxx.jl:142
 [4] include_relative(::Module, ::String) at .\loading.jl:464
 [5] include at .\sysimg.jl:14 [inlined]
 [6] include(::String) at E:\Users\DrKra\.julia\v0.7\Cxx\src\Cxx.jl:142
 [7] include_relative(::Module, ::String) at .\loading.jl:464
 [8] include(::Module, ::String) at .\sysimg.jl:14
 [9] anonymous at .\<missing>:2
while loading E:\Users\DrKra\.julia\v0.7\Cxx\src\typetranslation.jl, in expression starting on line 434
while loading E:\Users\DrKra\.julia\v0.7\Cxx\src\Cxx.jl, in expression starting on line 162

**Comment by DrKrar** [comment] 2017-09-28 22:13
This is the mater of the package in the latest  0.7.0-DEV.1816 on Win10

**Comment by ararslan** [comment] 2017-09-28 22:22
Can you do `Pkg.build("Cxx")` and try again?

**Comment by DrKrar** [comment] 2017-09-29 15:08
I already tried out Pkg.build("Cxx") and here is the result:

```julia> Pkg.build("Cxx")
INFO: Building Cxx
writing path.jl file
Tuning for julia installation at D:\Julia\Julia-0.7.0-DEV\bin with sources possibly at D:\Julia\Julia-0.7.0-DEV\bin\..\..
WARNING: is_apple is deprecated, use Sys.isapple instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:68
 [2] is_apple() at .\deprecated.jl:31
 [3] include_relative(::Module, ::String) at .\loading.jl:464
 [4] include at .\sysimg.jl:14 [inlined]
 [5] include(::String) at .\loading.jl:498
 [6] evalfile(::String, ::Array{String,1}) at .\loading.jl:493
 [7] cd(::getfield(Main, Symbol("##2#4")){String}, ::String) at .\file.jl:59
 [8] (::getfield(Main, Symbol("##1#3")))(::IOStream) at .\none:11
 [9] open(::getfield(Main, Symbol("##1#3")), ::String, ::String) at .\iostream.jl:194
 [10] eval(::Module, ::Expr) at .\sysimg.jl:53
 [11] process_options(::Base.JLOptions) at .\client.jl:298
 [12] _start() at .\client.jl:383
while loading E:\Users\DrKra\.julia\v0.7\Cxx\deps\build.jl, in expression starting on line 37
=================================================[ ERROR: Cxx ]==================================================

LoadError: could not load library "libLLVM-3.9.1"
The specified module could not be found.

while loading E:\Users\DrKra\.julia\v0.7\Cxx\deps\build.jl, in expression starting on line 39

=================================================================================================================

================================================[ BUILD ERRORS ]=================================================

WARNING: Cxx had build errors.

 - packages with build errors remain installed in E:\Users\DrKra\.julia\v0.7
 - build the package(s) and all dependencies with `Pkg.build("Cxx")`
 - build a single package by running its `deps/build.jl` script

=================================================================================================================```

**Comment by Gnimuc** [comment] 2017-09-30 13:51
Duplicate of #293 

It doesn't work on Windows since Julia-v0.5.

**Comment by skariel** [comment] 2018-06-27 10:11
confirming this is still the case with 0.7-beta

**Comment by Gnimuc** [comment] 2019-04-23 13:23
Cxx master can be successfully precompiled on 64-bit Windows, so I'm closing this. But Windows support is still in its early stage. Please browse issues that labeled `Windows` for further details.

**Closed by Gnimuc** 2019-04-23 13:23 UTC
