### ISSUE TITLE
Update screenshot for Julia 0.6

### ISSUE THREAD

**Issue by ufechner7** [JuliaInterop/Cxx.jl#381] opened 2018-05-12 15:12 UTC
Hello,
in Julia 0.6 there is no bytestring, String must be used instead.
In addition the info is missing, that <ctrl><c> can be used to go back
to Julia mode.
Uwe

**Comment by ararslan** [comment] 2018-05-12 19:18
Duplicate of #348.

**Closed** 2019-04-25 14:29 UTC
